repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: trailing-whitespace
    exclude: ^docs/
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: mixed-line-ending
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.0a6
  hooks:
  - id: pylint
    exclude: ^docs/
- repo: local
  hooks:
  - verbose: true
    require_serial: true
    name: check_mypy_deps
    language: python
    id: check_mypy_deps
    entry: python check_mypy_deps.py
    additional_dependencies:
    - tomli==2.0.1
    - pyyaml==6.0
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - additional_dependencies:
    - python-telegram-bot==20.3
    - gspread==5.1.1
    - oauth2client==4.1.3
    - pydantic==1.10.8
    - mypy-extensions==1.0.0
    - python-dotenv==0.19.2
    - sqlalchemy==2.0.15
    - loguru==0.5.3
    args:
    - --no-strict-optional
    exclude: ^(tests/|sandbox/|docs/)
    files: ^bot/.*\.py$
    id: mypy
    language: python
    name: mypy
    require_serial: true
    types:
    - python
    verbose: true
- repo: https://github.com/python-poetry/poetry
  rev: 1.5.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    args:
    - --without-hashes
    - -f
    - requirements.txt
    - -o
    - requirements.txt
